### ISSUE TITLE
想记录并在控制台展示.链路的参数和返回.应该修改哪里.

### ISSUE THREAD

**Issue by SandyJiang** [OpenSkywalking/skywalking#339]
目前在看的版本是3.1.求指点.

**Comment by wu-sheng** [comment]
需要修改每个插件的埋点。比如入口HTTP请求，需要修改Tomcat插件，SQL调用修改jdbc插件等。可以通过activeSpan#tag或activeSpan#log来记录参数。请注意这里是针对所有通过埋点的方法，所以序列化性能是十分重要的。
