### ISSUE TITLE
Add linkerd plugin. Provided by dangdang.com

### ISSUE THREAD

**Issue by hanahmily** [OpenSkywalking/skywalking#379]
[Linkerd](https://linkerd.io) is a transparent service mesh, designed to make modern applications safe and sane by transparently adding service discovery, load balancing, failure handling, instrumentation, and routing to all inter-service communication.

The plugin is designed to extract  trace data from linkerd internal to the sky-walking collectors.

**Comment by wu-sheng** [comment]
Thanks for your contribution, we will wait for your pull request. The skywalking 3.3 will be a reserved version for you and dangdang, which includes linkerd plugin, and hopefully Sharding-JDBC as well.

**Comment by wu-sheng** [comment]
Closing this.
