### ISSUE TITLE
The elastic modules for aggregation contain id only

### ISSUE THREAD

**Issue by wu-sheng** [OpenSkywalking/skywalking#400]
Right now, for avoiding uncompressed serviceName(OperationName) and peer(IP:port), we build the elastice aggregation modules, which contain both String(name) and id. This is not good for query.

So, we should set a buffer(memory and file) for this type of serviceName and peer, wait for exchange(compression) .

This will make the elastic modules and query easier for everyone.

**Comment by peng-yongsheng** [comment]
Done
