### ISSUE TITLE
Make sure no literal operationName and peer in the storage 

### ISSUE THREAD

**Issue by wu-sheng** [OpenSkywalking/skywalking#423]
In 3.2, we provided a very complex storage modules, which will trigger many bugs. So we should make them easier. For that, create a buffer mechanism, including memory and disk buffer, to make sure the operationName and peer have been exchanged into ids, before saving them.

After we done, we can remove the complex query logic, step by step, in the several next versions, e.g. 3.2.2, 3.2.3

I think this is the most important work at collector side in 3.2.1

@pengys5 Hope this works well.

cc @ascrutae

**Comment by peng-yongsheng** [comment]
Done
