### ISSUE TITLE
Support H2 storage modules at Collector Side

### ISSUE THREAD

**Issue by wu-sheng** [OpenSkywalking/skywalking#424]
@pengys5 has already provided the H2 modules, but didn't provide the dao to access(read/write) data. 

After we have this, we can start up collector without es, and of course, don't support cluster mode.

**Comment by clevertension** [comment]
awesome!!!, it is easy for development, i can contribute with this feature

**Comment by wu-sheng** [comment]
@clevertension We just need to support memory/file mode H2. This is an easy implementation for that collector can run standalone truly, without any dependency env.

**Comment by wu-sheng** [comment]
@clevertension Is there any update about your progress? I am checking the features can be released in version 3.2.3, which will be released a week later, and it should be the last version of 3.2.x (except hotfix version) 

#423 is the highest priority feature in 3.2.3

**Comment by clevertension** [comment]
i am doing it, the work is a bit large

**Comment by wu-sheng** [comment]
@clevertension Please give us some updates at the end of this week. And we can decide the released version for this feature.

**Comment by clevertension** [comment]
https://github.com/OpenSkywalking/skywalking/pull/519
it is done!

**Comment by wu-sheng** [comment]
@peng-yongsheng I will keep this open, since you still need do some adjustments for H2 storage module, right?

**Comment by peng-yongsheng** [comment]
Done
