### ISSUE TITLE
cannot hook the @GetMapping, @PostMapping... with spring-mvc-4.x plugin

### ISSUE THREAD

**Issue by clevertension** [OpenSkywalking/skywalking#465]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2

### What version of your OS?
macOS

### What version of your JRE?
1.7, 1.8

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

this is a new feature with @GetMapping, @PostMapping since spring 4.3, so we should support it

```
if (requestURL == null) {
            RequestMapping methodRequestMapping = method.getAnnotation(RequestMapping.class);
            if (methodRequestMapping.value().length > 0) {
                requestURL = methodRequestMapping.value()[0];
            } else {
                requestURL = "";
            }
            pathMappingCache.addPathMapping(method, requestURL);
            requestURL = pathMappingCache.findPathMapping(method);
        }
```

![image](https://user-images.githubusercontent.com/346723/30898046-e4bb25fe-a38b-11e7-950b-373f6a4dc9c9.png)

**Comment by ascrutae** [comment]
I think that we can abstract parent class  and each sub class to fetch the request URL.

**Comment by wu-sheng** [comment]
@clevertension This is an improvement. We can provide more plugins for these annotations.

**Comment by wu-sheng** [comment]
@clevertension, are you doing this?

**Comment by clevertension** [comment]
yes,i am doing this

**Comment by wu-sheng** [comment]
Good to know. Thanks. Pay attention for #478. When you are testing a controller effected by multi  annotations, you are possible to face the situation, which the pr tries to suppot.

**Comment by wu-sheng** [comment]
#478 has already merged. cc @clevertension

**Comment by wu-sheng** [comment]
Maybe close this?

**Comment by clevertension** [comment]
yes, we can close it
