### ISSUE TITLE
docker-compose.yml文件的一些小问题

### ISSUE THREAD

**Issue by qw2283345** [OpenSkywalking/skywalking#492]
1、docker仓库版本未同步更新，web-ui与collector里的最新版本不一致
2、docker-compose.yml文件里的skywalking/skywalking-ui:3.2.3-2017 对应的docker hub名称应为 skywalking/sky-walking-ui
都是小问题，反馈一下

**Comment by ascrutae** [comment]
@qw2283345 master中的docker-compose.xml的中正准备发布的版本镜像，docker仓库中只有在这个版本发布的时候才能被同步。skywalking/sky-walking-ui这个在3.2版本的名字已经修改成skywalking/skywalking-ui

**Comment by wu-sheng** [comment]
@qw2283345 在最近项目经历过改名。请确认下镜像和docker-compose在最新版本是否能正常运行？

**Comment by qw2283345** [comment]
@ascrutae @wu-sheng 我今天再尝试一下部署docker，结果再反馈，谢谢
