### ISSUE TITLE
无法获取Track Stack数据

### ISSUE THREAD

**Issue by damacheng009** [OpenSkywalking/skywalking#494]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
最新版本

### What version of your OS?
win7

### What version of your JRE?
JDK8

### What company or project?
sevlet测试web小程序+jetty9最新版本

### What did you do?
es的data目录，见附件。
[data.zip](https://github.com/wu-sheng/sky-walking/files/1370734/data.zip)

**Comment by wu-sheng** [comment]
#506 and #502 trigger this issue together. This is going to fix in 3.2.3

**Comment by ascrutae** [comment]
This issue has been fixed in PR #506 and #502
