### ISSUE TITLE
Tomcat8 + spring mvc：one http request create on span?

### ISSUE THREAD

**Issue by neeuq** [OpenSkywalking/skywalking#498]
Please answer these questions before submitting your issue.
### What version of sky-walking are you using?
最新版本

### What did you do?
技术点：tomcat8 + spring mvc
可能是我不太理解设计思路，一个http请求只会产生一个span，而不是tomcat 8和spring controller在各自的切面产生各自的span。虽各自类都能正常拦截，但引用的是同一个span，是不是同一个线程的关系吗？

**Comment by wu-sheng** [comment]
一次调用中，tomcat8和springmvc都属于EntrySpan，所以会进行自动合并。这是我们的一个性能优化策略。

**Comment by neeuq** [comment]
谢谢，最近在学习该框架源码，准备用于生产监控使用。
架构设计简洁清晰，代码量也不多。赞！

**Comment by wu-sheng** [comment]
好的，欢迎有问题随时讨论，并反馈事情情况。目前准备使用的公司是？

**Comment by neeuq** [comment]
深圳卫盈智信科技有限公司
刚开始研究，准备先在测试环境先使用
