### ISSUE TITLE
wiki: 3.2-supported-list need update

### ISSUE THREAD

**Issue by wendal** [OpenSkywalking/skywalking#505]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2.1

### What version of your OS?
windows

### What version of your JRE?
1.8

### What company or project?
广州文尔

### What did you do?
sky-walking 3.2.1 support nutz web/http, but not display in `3.2-supported-list` yet

**Comment by wu-sheng** [comment]
Based on release notes, nutz framework was supported in 3.2.1 . And `3.2-supported-list` doesn't represent all components supported in 3.2.x, it is simple meaning the first version of 3.2 series.

Check here: https://github.com/OpenSkywalking/skywalking/releases/tag/v3.2.1

**Comment by wu-sheng** [comment]
@wendal Can I close this?
