### ISSUE TITLE
Provide plugin for rocketmq

### ISSUE THREAD

**Issue by vwyuheng** [OpenSkywalking/skywalking#51]

**Comment by wu-sheng** [comment]
New RocketMQ git moves to https://github.com/apache/incubator-rocketmq.
Wait for RocketMQ next release. @vongosling

**Comment by wu-sheng** [comment]
UI and Analysis component have no time to support the batch mode. Delay this feature again.

**Comment by vongosling** [comment]
Is it OT plugin？

**Comment by wu-sheng** [comment]
I am sorry to say, it isn't. This is just about sky-walking tracer implementation. As our team has no time on trace visualization in batch mode, we have to delay it. 

In OT spec, we already have tags about message bus. And OT supported frameworks are here: https://github.com/opentracing-contrib/meta. Happy to have RocketMQ.

**Comment by wu-sheng** [comment]
#571 will be merged soon, @vongosling . we are going to support RocketMQ by using our auto instrument mechanism, not OT.

**Comment by vongosling** [comment]
@wu-sheng Cool
