### ISSUE TITLE
apm-collector-core项目下ResourceUtils类是不是有点小问题

### ISSUE THREAD

**Issue by neeuq** [OpenSkywalking/skywalking#510]
### What version of sky-walking are you using?
最新版本

### What version of your JRE?
java 8

我们现在想把application.yml集成至jar中，发现ResourceUtils读取不到jar里面的资源，看程序的愿意是可以从jar中读取的。是不是返回InputStreamReader更合理点？

**Comment by peng-yongsheng** [comment]
这个文件之前没想过要打到jar包中，你可以帮忙改一下，jar包内外得都可以读。

**Comment by wu-sheng** [comment]
@neeuq Could you send a pull request to fix?

**Comment by wu-sheng** [comment]
Ref #511
