### ISSUE TITLE
[Voting] Promoting @hanahmily as a member of Committer Team

### ISSUE THREAD

**Issue by wu-sheng** [OpenSkywalking/skywalking#515]
This is first Voting since **Open Skywalking Organization** begins to work.

# Proposal
@hanahmily is a senior architect in Dangdang.com, who help us a lot:
* Contribute new plugins of dangdang open source project. 
* Running skywalking in dangdang.com system.
* Provide technical suggestions for skywalking
* Take part in skywalking more than 6 months, including offline works.

Please take vote for the promoting. @OpenSkywalking/pmc @OpenSkywalking/committer-team 

___

All contributors have the chance to join PMC or committer team, which depends on the your contribution, and proposal by one of the existing member.

cc @mircoteam @clevertension @xcaspar @wendal @zhangkewei @IluckySi @wendal

**Comment by wu-sheng** [comment]
FYI @terrymanu , hope @hanahmily can contribute more between skywalking and dangdang ecosystem.

**Comment by peng-yongsheng** [comment]
+1

**Comment by wu-sheng** [comment]
+1

**Comment by adriancole** [comment]
I am not skywalking but I love what you are doing. Nice community work!

**Comment by ascrutae** [comment]
+1

**Comment by clevertension** [comment]
+1

**Comment by IluckySi** [comment]
+1

**Comment by bai-yang** [comment]
+1

**Comment by wu-sheng** [comment]
all @OpenSkywalking/pmc and @OpenSkywalking/committer-team  have voted. And we have four yes. So congrate @hanahmily to join the committer team. I will send the invitation to @hanahmily. anf update the team list.

Thanks, every one.
