### ISSUE TITLE
druid + mysql：compatibility problem?

### ISSUE THREAD

**Issue by neeuq** [OpenSkywalking/skywalking#546]
### What version of sky-walking are you using?
(the latest version of sky-walkiing) + druid-1.0.17.jar + mysql-connector-java-5.1.13.jar
----------------------------------------------------

When druid database source init, he will validate every connection he create. He invoke method  **pingInternal** in **com.mysql.jdbc.MySQLConnection** as default.But using sky-walking,the connection is proxy by **org.skywalking.apm.plugin.jdbc.SWConnection**,then druid execute the below code has different result.
// clazz == com.mysql.jdbc.MySQLConnection
// conn == org.skywalking.apm.plugin.jdbc.SWConnection
     clazz.isAssignableFrom(conn.getClass())
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
也就是说druid框架在检测数据库连接时想用到MySQLConnection的特有方法，导致程序有点不兼容，不使用ping方法检查连接。刚才druid-1.0.17的检测sql为空报错，之后的版本都有默认的sql。
我想问一下，有没有什么办法从sky-walking框架层次来解决这个问题，尽可能兼容已有的应用，同时不想增加对mysql-connector-java包的依赖。目前SWConnection只是java.sql.Connection的子类，没想到特别好的方法。

其他解决方法：其实可以升级druid框架或者增加检测sql="select 1"解决问题。
 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>  

        ` if (usePingMethod) {
            if (conn instanceof DruidPooledConnection) {
                conn = ((DruidPooledConnection) conn).getConnection();
            }
            if (conn instanceof ConnectionProxy) {
                conn = ((ConnectionProxy) conn).getRawObject();
            }
            if (clazz.isAssignableFrom(conn.getClass())) {
                if (validationQueryTimeout < 0) {
                    validationQueryTimeout = DEFAULT_VALIDATION_QUERY_TIMEOUT;
                }
                try {
                    ping.invoke(conn, true, validationQueryTimeout);
                    return true;
                } catch (InvocationTargetException e) {
                    Throwable cause = e.getCause();
                    if (cause instanceof SQLException) {
                        return false;
                    }
                    LOG.warn("Unexpected error in ping", e);
                    return false;
                } catch (Exception e) {
                    LOG.warn("Unexpected error in ping", e);
                    return false;
                }
            }
        }`

**Comment by wu-sheng** [comment]
是的，你可以尝试一下3.2.3版本，我们已经不再替换Connection.

**Comment by neeuq** [comment]
更新了代码，这个应该没问题了，发现代码结构有些变动。补充个问题：
1、是基于什么考虑，把jdbc监控修改了
2、插件包现在放在外面了，是方便增减，都实际部署时感觉集成至一个jar包更方便，纠结了

**Comment by wu-sheng** [comment]
> 1、是基于什么考虑，把jdbc监控修改了

主要解决的是这种连接校验的问题。除了Druid之外，有些datasource也监测这个。

> 2、插件包现在放在外面了，是方便增减，都实际部署时感觉集成至一个jar包更方便，纠结了

这个我个人认为，增减是主要特性，你只是多了一个`tar`的操作，我觉得没有必要纠结。

另外，因为此问题已解决，我将关闭此问题。
