### ISSUE TITLE
mysql: prepareStatement()

### ISSUE THREAD

**Issue by neeuq** [OpenSkywalking/skywalking#554]
### What version of sky-walking are you using?
sky-walking.3.23 + mysql-connector-java-5.1.39.jar 
---------------------------------------------------------------------------------------------------
场景：当用到数据库自增特性时，需要返回主键值。
mysql驱动包方法里面java.sql.PreparedStatement --> com.mysql.jdbc.PreparedStatement的强转，报
org.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to com.mysql.jdbc.PreparedStatement。

------the test code---------------------------------------------------------------------------
`/**
CREATE TABLE `application` (
  `application_id` int(11) NOT NULL AUTO_INCREMENT,
  `application_code` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`application_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
*/
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
public class MysqlTest {

    public static void main(String[] args) throws Exception {
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection(
                "jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8", "root",
                "admin");
        PreparedStatement p =
                conn.prepareStatement("insert into application(application_code)values(?)",
                        Statement.RETURN_GENERATED_KEYS);
        p.setString(1, "test");
        p.executeUpdate();
    }
}
`
------the error message---------------------------------------------------------------------------
Exception in thread "main" java.lang.ClassCastException: org.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to com.mysql.jdbc.PreparedStatement
	at com.mysql.jdbc.ConnectionImpl.prepareStatement$original$tGQ8d9jZ(ConnectionImpl.java:4080)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement$original$tGQ8d9jZ$accessor$zcaGMKrY(ConnectionImpl.java)
	at com.mysql.jdbc.ConnectionImpl$auxiliary$L8yu6g5h.call(Unknown Source)
	at org.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:92)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java)
	at com.yiqiniu.apm.MysqlTest.main(MysqlTest.java:21)

**Comment by wu-sheng** [comment]
@ascrutae 这个还需要实现更深一层……你悲剧了……

**Comment by wu-sheng** [comment]
@neeuq 我们会调整一下实现。因为没做一层，就增加代码量和调试复杂度，本来不想这么做的。

**Comment by neeuq** [comment]
能理解，完全不知道接口的底层实现类可能在干什么，感觉用(new SWPreparedStatement)这种代理的方法有点危险。

是准备要怎么修改，直接对com.mysql.jdbc.PreparedStatement和com.mysql.cj.jdbc.PreparedStatement做增强，并拦截指定的方法？

**Comment by wu-sheng** [comment]
> 是准备要怎么修改，直接对com.mysql.jdbc.PreparedStatement和com.mysql.cj.jdbc.PreparedStatement做增强，并拦截指定的方法？

@ascrutae 会使用字节码的方式修改这两个类，取代SW*这样的类型，保证类型匹配。SW*主要是想保持插件逻辑简单，可读性高，全部使用字节码，可读性下降很多。

**Comment by ascrutae** [comment]
ref PR: #562

**Comment by wu-sheng** [comment]
#562 merged, and support mysql-connector 5.x, 6.x in new ways. cc @ascrutae
