### ISSUE TITLE
AgentPackagePath can't find path in workspace?

### ISSUE THREAD

**Issue by neeuq** [OpenSkywalking/skywalking#556]
org.skywalking.apm.agent.core.boot.AgentPackagePath.findPath()：
line 71:
String classLocation = urlString.substring(urlString.indexOf("file:"), urlString.length() - classResourcePath.length());

**Because the value of "classLocation" is startwith "file:",is url type,and it can't pass follow unit test**

----------this is unit test----------------------------------------------------
@Test
    public void testGetPath() throws AgentPackageNotFoundException {
        File file = AgentPackagePath.getPath();
        Assert.assertTrue(file.exists());
    }

**Comment by wu-sheng** [comment]
Yes, this API only works for jar file, for now. Do you have any suggestion? As you known, in IDE, the classes and resources files in separated folders, if you want to make sure this API works, it is totally a different logic.

**Comment by neeuq** [comment]
I can't understand 'isInJar'  in follow code.I guess it works no matter in Jar、IDE workspace.
And when isInJar is false, there is something wrong run it. 
----------------------------------------------------------------------------------------------
            if (isInJar) {
                urlString = urlString.substring(urlString.indexOf("file:"), insidePathIndex);
                File agentJarFile = null;
                try {
                    agentJarFile = new File(new URL(urlString).getFile());
                } catch (MalformedURLException e) {
                    logger.error(e, "Can not locate agent jar file by url:" + urlString);
                }
                if (agentJarFile.exists()) {
                    return agentJarFile.getParentFile();
                }
            } else {
                String classLocation = urlString.substring(urlString.indexOf("file:"), urlString.length() - classResourcePath.length());
                return new File(classLocation);
            }
        }

**Comment by wu-sheng** [comment]
```java
        } else {
            String classLocation = urlString.substring(urlString.indexOf("file:"), urlString.length() - classResourcePath.length());
            return new File(classLocation);
        }
```

I can't make sure the `else` part works. If you are interesting in this. You can run some tests, and submit a pull request to fix this. But I am pretty sure, that is complicated, the easy way to make sure `loadConfigFromAgentFolder` is that, when you can't get the file path in Jar mode, use `Class#getResourceAsStream` instead.

**Comment by wu-sheng** [comment]
Closing this. Since this question stays cold in more than one month.
