### ISSUE TITLE
java8永久代名称对应不上

### ISSUE THREAD

**Issue by neeuq** [OpenSkywalking/skywalking#558]
java8环境下：
org.skywalking.apm.agent.core.jvm.memorypool.MemoryPoolModule下面对于永久代的定义是不是有问题，在测试中java8永久代的名称变成Compressed Class Space，es里面都没有永久代的数据。
---------------------------------------------------------------------------------------

    @Test
    public void testJVM() {
        List<MemoryPoolMXBean> beans = ManagementFactory.getMemoryPoolMXBeans();
        for (MemoryPoolMXBean bean : beans) {
            System.out.println(bean.getName());
            System.out.println(bean.getUsage());
        }
    }

**Comment by wu-sheng** [comment]
你可以看一下这个`org.skywalking.apm.agent.core.jvm.memorypool.MemoryPoolProvider`和`org.skywalking.apm.agent.core.jvm.memorypool.MemoryPoolModule`，他是找收集器类型匹配，然后再找内存区。你看一下是哪一集不对。而且要看看在Java8和java7，是不是调整下监控性。目前，如果是CMS收集器，我取得是`Metaspace`的空间。

**Comment by neeuq** [comment]
这是我在测试环境中打印出的java8 jvm各区的名称：
Code Cache
Metaspace
Compressed Class Space
PS Eden Space
PS Survivor Space
PS Old Gen

跟org.skywalking.apm.agent.core.jvm.memorypool.ParallelCollectorModule有点不太吻合，主要是
PS Perm Gen --> Compressed Class Space, 之前是不是没考虑各版本间名称有变化。

**Comment by wu-sheng** [comment]
如果要兼容不同名称的情况，估计要一个更复杂的适配机制。

**Comment by wu-sheng** [comment]
已经提交到重构分之`feature/collector-modelization`，支持匹配多个名称。
