### ISSUE TITLE
使用futureStub调用远程grpc服务时agent报错

### ISSUE THREAD

**Issue by SeriousMa** [OpenSkywalking/skywalking#569]
![image](https://user-images.githubusercontent.com/464213/32359004-6f123f5a-c018-11e7-883d-51fbc77d9a03.png)

**Comment by SeriousMa** [comment]
远程服务shutdown时报错
![image](https://user-images.githubusercontent.com/464213/32359061-dfcb5448-c018-11e7-88c0-aaf32d9afdef.png)

**Comment by SeriousMa** [comment]
一个timer线程的blocking的心跳请求 web显示failed
![image](https://user-images.githubusercontent.com/464213/32359083-fd79626e-c018-11e7-9ebf-3611d4375e49.png)

**Comment by wu-sheng** [comment]
`futureStub` is new to us. Thanks for your reporting.

**Comment by ascrutae** [comment]
Got it

**Comment by ascrutae** [comment]
This issue has been fixed in PR #653

**Comment by ascrutae** [comment]
Colse this issue
