### ISSUE TITLE
RestTemplate Plugin don't works well

### ISSUE THREAD

**Issue by ascrutae** [OpenSkywalking/skywalking#597]

**Comment by wu-sheng** [comment]
The classloader mechanism had been changed in 3.2.3 released. In former days, the classloader of classes in plugin jars are different with the classes of the enhanced classes. That is a big change. So you can't use the same package name to access the a `package-level` class.

This need to fix fast, to make sure the plugins works perfectly.

**Comment by wu-sheng** [comment]
FYI @OpenSkywalking/pmc @OpenSkywalking/committer-team @OpenSkywalking/huawei-devcloud-contributor-team Please pay attention for my comments ^^^ .

**Comment by ascrutae** [comment]
This issue was fixed in PR #598 , closed it.
