### ISSUE TITLE
咨询agent打包的问题

### ISSUE THREAD

**Issue by myoss** [OpenSkywalking/skywalking#628]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2.5

### What version of your OS?
CentOS 7

### What version of your JRE?
1.8

### What company or project?
ali

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

#### 问题1
agent.jar包有16mb多，主要是org.skywalking.apm.dependencies这个目录下面的文件很大，请问下这个目录中将第三方的class的package都被加上了 “org.skywalking.apm.dependencies” 前缀，主要作用是什么？

#### 问题2
因为agent的文件，是被分成3个目录（目录中包含多个jar包或者配置文件）+ skywalking-agent.jar 这个文件，现在想用这个来部署到服务器是非常痛苦的（生产实例太多），想做成一个flat jar（类似spring boot jar包），这样项目中直接依赖即可，升级和发布都会很方便，能否考虑下？

#### 问题3
能否多点架构设计的文档，便于快速了解整个项目，进行二次开发，谢谢。

**Comment by wu-sheng** [comment]
> 问题1
agent.jar包有16mb多，主要是org.skywalking.apm.dependencies这个目录下面的文件很大，请问下这个目录中将第三方的class的package都被加上了 “org.skywalking.apm.dependencies” 前缀，主要作用是什么？

org.skywalking.apm.dependencies是为了保证探针依赖的完全独立性，避免和应用程序依赖树冲突。

> 问题2
因为agent的文件，是被分成3个目录（目录中包含多个jar包或者配置文件）+ skywalking-agent.jar 这个文件，现在想用这个来部署到服务器是非常痛苦的（生产实例太多），想做成一个flat jar（类似spring boot jar包），这样项目中直接依赖即可，升级和发布都会很方便，能否考虑下？

你说的fat jar，老版本的探针很早就支持，但是这并不给你带来你理想中的方便。因为探针有Plugin可能和应用冲突，需要移除；你可能开发非开源的plugin，此时打包会困难；配置文件无法防止和方便修改。生产实例的部署，我们一般建议采用shell完成安装脚本，进行自动化安装和拷贝。

> 问题3
能否多点架构设计的文档，便于快速了解整个项目，进行二次开发，谢谢。

开源项目的快速迭代，我们一般保持接口稳定，而非架构代码的绝对稳定，所以，暂时无法以稳定文档的方式提供。

**Comment by wu-sheng** [comment]
历史版本读取方式完全不同，需要回退部分核心代码才能完成相关功能。skywalking团队不建议采用该方式，因为运作机制不同，很难保证目前的插件能够在老机制下正常运行。
