### ISSUE TITLE
[Big Change] Change Core data structure, ref and span related.

### ISSUE THREAD

**Issue by wu-sheng** [OpenSkywalking/skywalking#629]
Hi @OpenSkywalking/pmc @OpenSkywalking/committer-team , as you known, we are going to support MQ formally. In that, we are going to face the batch process and multi ref in the real world.

The recent ref is in the segments, but in MQ consumers, there may be a chance to facing multi entry span in a single segment, each one is different layer, such as HTTP and MQ. At that moment, the refs belong to different spans.

So I am going to refactor codes and change the core data structure. Moving the ref from segment into span(EntrySpan only). And change the uplink network protocol. 

I am creating a branch, named `feature/new-batch-model`, to hold all refactor changes from agent and collector. Every related pull requests, please sent the target to it.

**Comment by wu-sheng** [comment]
Branch created: https://github.com/OpenSkywalking/skywalking/tree/featuren/new-batch-model

**Comment by wu-sheng** [comment]
Branch created: https://github.com/OpenSkywalking/skywalking/tree/feature/new-batch-model

**Comment by peng-yongsheng** [comment]
I merge this branch into the [alerting](https://github.com/OpenSkywalking/skywalking/tree/feature/alerting) branch. Develop it with alerting function together.

**Comment by wu-sheng** [comment]
Closing this issue. The new **Core data structure** has been accepted. And 5.0 will base on that.
