### ISSUE TITLE
访问路径中带下划线,UI界面不显示OperationName

### ISSUE THREAD

**Issue by minlingchao1** [OpenSkywalking/skywalking#636]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2.5

### What version of your OS?
Mac OS 10.13.1 

### What version of your JRE?
1.8

### What company or project?
杭州云贝网络

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
创建接口
@RequestMapping("/single_send")
@RequestMapping("/singlesend")
第一个不会显示OperationName 第二个会显示

如图所示
访问路径带下划线
![image](https://user-images.githubusercontent.com/9193693/33511386-ee6a2210-d754-11e7-827b-e9cd75fb9778.png)
不带下划线
![image](https://user-images.githubusercontent.com/9193693/33511398-13c92fce-d755-11e7-85a2-54334e5c5d1f.png)

**Comment by wu-sheng** [comment]
@peng-yongsheng It looks like an UI bug?

**Comment by minlingchao1** [comment]
@wu-sheng  这个不是UI的bug，我看过获取数据的接口，返回的数据中serviceName就是空，所以应该是在collector中出现问题了

**Comment by peng-yongsheng** [comment]
@minlingchao1 There is no problem with your analysis. I probably know why, so I will check it.

**Comment by minlingchao1** [comment]
@peng-yongsheng 能尽快修复一下么？我这边还要用，谢谢啦

**Comment by zuohl** [comment]
@minlingchao1 你不显示OperationName 访问的地址发出来看看

**Comment by wu-sheng** [comment]
@minlingchao1 I am closing this issue, since we have the same issue in English. Check #642
