### ISSUE TITLE
运行一段时间后collector进程Cpu利用率100%,　前端查询速度变慢

### ISSUE THREAD

**Issue by alex8224** [OpenSkywalking/skywalking#640]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
v3.2.5

### What version of your OS?
centos 6.5 64bit

### What version of your JRE?
java8

### What did you do?
查询threadump，发现collector进程有５７个线程在blocked状态

可以通过 http://fastthread.io/my-thread-report.jsp?p=c2hhcmVkLzIwMTcvMTIvNC8tLTE5OTY4LmR1bXAtLTctMzEtMjg= 查看详细的threadump分析报告

**Comment by wu-sheng** [comment]
@alex8224 Can you provide more info?

1. Is collector in cluster mode?
1. Is collector using elastic search as storage implementation?
1. Is elastic search in cluster mode?

**Comment by alex8224** [comment]
1. no
2. no use default H2
3. no

application.yml for single collector:

#cluster:
#  zookeeper:
#    hostPort: localhost:2181
#    sessionTimeout: 100000
naming:
  jetty:
    host: 10.0.98.22
    port: 10800
    context_path: /
remote:
  gRPC:
    host: 10.0.98.22
    port: 11800
agent_gRPC:
  gRPC:
    host: 10.0.98.22
    port: 11800
agent_jetty:
  jetty:
    host: 10.0.98.22
    port: 12800
    context_path: /
agent_stream:
  default:
    buffer_file_path: ../buffer/
    buffer_offset_max_file_size: 10M
    buffer_segment_max_file_size: 500M
ui:
  jetty:
    host: 10.0.98.22
    port: 12800
    context_path: /
#storage:
#  elasticsearch:
#    cluster_name: CollectorDBCluster
#    cluster_transport_sniffer: true
#    cluster_nodes: localhost:9300
#    index_shards_number: 2
#    index_replicas_number: 0

**Comment by wu-sheng** [comment]
@alex8224 In the  first line of `standalone` documents, you will see, we just recommend using H2 storage for **demonstration and preview only**. Please be advised.

**Comment by alex8224** [comment]
yes, I see.

**Comment by wu-sheng** [comment]
Closing this issue. If you have more question, please submit new issue.
